### ISSUE TITLE
Roundup: [oss-security] audiofile: multiple crashes

### ISSUE THREAD

**Issue by grahamc** [NixOS/security#20]
Here is a report from the oss-security mailing list for [Vulnerability Roundup 27](https://github.com/NixOS/nixpkgs/issues/24319).

[Skip to First Email](#first-email)

# Instructions:
## Identification
Identify if we have the software, in 16.09, 17.03, and unstable. Then determine if we are vulnerable, and make a comment with your findings. It can also be helpful to specify if you think there is a patch, or if it can be fixed via a general update.

Example:

```
unstable: we are not vulnerable (link to the package)
17.03: we are vulnerable (link to the package)
16.09: we don't have it packaged
```

**IMPORTANT**: If you believe there are possibly related issues, bring them up on the _parent_ issue!

## Patching
Start by commenting on this issue saying you're working on a patch. This way, we don't duplicate work.

If you open a pull request, tag this issue _and_ the master issue for the roundup.

If you commit the patch directly to a branch, please leave a comment on this issue with the branch and the commit hash, example:

```
fixed:

release-16.09: abc123
```

[Skip to First Email](#first-email)

## Upon Completion ...
 - [ ] Update Graham's database

## Info

_Triage Indicator:_

```
-needs-triage +roundup27 thread:0000000000003e00
```

 - File Search: https://search.nix.gsc.io/?q=audiofile&i=fosho&repos=nixos-nixpkgs
 - GitHub Search: https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=audiofile+in%3Apath&type=Code

Should the search term be changed from `audiofile`? Suggest a new package search by commenting:

```
-suggested:audiofile +suggested:correctPackageName thread:0000000000003e00
```

Known CVEs: 

---

<a name="first-email"></a>
[Skip to End](#end)

##### Sun, 26 Feb 2017 11:43:25 +0000 "Agostino Sarubbo" <ago-at-gentoo.org>, `987433.508128987-sendEmail@localhost`

    Hello all.
    
    I discovered multiple crashes in the audiofile library.
    The maintainer was informed privately, I didn't see reactions and all details are public on my blog.
    I posted them to the cveform too, but I didn't get response.
    I'll send update if something will change. 
    
    --
    Agostino Sarubbo
    Gentoo Linux Developer
    
    

[Skip to End](#end)

---

<a name="end"></a>

**Comment by fpletz** [comment]
This is just a reminder that the audiofile developer hasn't reponded and not a new security issue. See the other audiofile issues.
